### ISSUE TITLE
pgxr写存过，里面怎么写sql带临时表？

### ISSUE THREAD

**Issue by wonb168** [clia/pgxr#4]
现在用plsql写的跑的不快，想试试rust写。但不知道这种用rust咋写？
里面的逻辑大概是：
create temp table a as ...
create temp table b as select * from a join ...
insert into t select * from b

**Comment by clia** [comment]
只要是SQL，都可以直接在存储过程里写的，一条一条执行就可以了。

现在这个项目已基本不维护了，建议看看：https://github.com/tcdi/pgx
比这个强大很多。

**Comment by wonb168** [comment]
plsql的存过太慢了，想用rust写
